# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6d5d619e77fb3f630e86fad63a48a1ea1c9dcf7191419d172f91909f27a735e2cde71f683d86872e25b4a50cfd9634c3642ee2703e36c7e8b172436f1fda8ca

test:
  secret_key_base: 04dcfb6ccea67fe29e126322cb4bb95b5a9ff94ae4b59071c874733cbd360e4c4a390fd8ecc745bba4f0510d59eb1cede45434af5ea4b01c9e52a8e4fabe43c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
